# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: security-playground
  namespace: security-lab
  labels:
    app: security-playground
spec:
  selector:
    app: security-playground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
